name: mirza_shop
description: "Mirza Shop"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  path: ^1.9.0
  path_provider: ^2.1.2
  mobile_scanner: '>=4.0.1 <8.0.0'
  image_picker: '>=1.0.7 <2.0.0'
  flutter_animate: ^4.5.0
  intl: '>=0.19.0 <1.0.0'
  uuid: '>=4.3.3 <5.0.0'
  shared_preferences: ^2.2.2
  permission_handler: '>=11.3.0 <13.0.0'
  web_socket_channel: '>=2.4.4 <4.0.0'
  archive: '>=3.4.10 <5.0.0'
  file_picker: '>=6.1.1 <10.0.0'
  local_auth: '>=2.2.0 <3.0.0'
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=3.0.1 <6.0.0'

flutter:
  uses-material-design: true
