name: ساخت APK اندروید

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: دانلود کد
        uses: actions/checkout@v4

      - name: نصب Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: نصب Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: آماده‌سازی پروژه
        run: |
          flutter create --platforms=android . --org com.mirzashop --project-name mirza_shop
          flutter pub get

      - name: ساخت APK
        run: flutter build apk --release

      - name: آپلود APK
        uses: actions/upload-artifact@v4
        with:
          name: MirzaShop-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk
